name: Static Checks

on:
  push:

jobs:
  test:
    name: Static Checks
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        container:
        - 'python:3.7-slim'
        - 'python:3.8-slim'
        - 'python:3.9-slim'

    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v1
      - name: Install host dependencies
        run: |
          apt-get -qq update
          apt-get install -qq gcc git
          rm -rf /var/lib/apt/lists/*
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Check format with black
        run: poetry run black . --check
      - name: Lint with flake8
        run: poetry run flake8 .
      - name: Sort imports with isort
        run: poetry run isort .
